/**
 * Generate ed25519 test vectors for yeti_wells::attestation_tests.
 *
 * `sui::ed25519::ed25519_verify` only verifies on-chain; signing must happen off-chain. This emits a
 * FIXED keypair's pubkey + real signatures over BCS-encoded MilestoneReports, as Move `x"..."` literals.
 *
 * The signed BCS bytes MUST byte-match Move's `bcs::to_bytes(&MilestoneReport)` (same field order/types).
 * The project id below is the DETERMINISTIC id that `attestation_tests::setup()` produces (from the
 * probe_project_id test). If you change that setup, re-run the probe and regenerate.
 *
 * Run:  node gen_attestation_vector.ts
 */
import { bcs } from '@mysten/sui/bcs';
import { Ed25519Keypair } from '@mysten/sui/keypairs/ed25519';

// Deterministic project id from attestation_tests::probe_project_id.
const PROJECT_ID = '0x63d9a65220318469fb169034d8a011eae3f014fed2a1f8c006183e2ece3c3975';
const WRONG_PROJECT_ID = '0x000000000000000000000000000000000000000000000000000000000000dead';
const TS = 1_000n;

// Fixed 32-byte seed -> reproducible keypair.
const seed = new Uint8Array(32);
for (let i = 0; i < 32; i++) seed[i] = (i * 7 + 13) & 0xff;
const keypair = Ed25519Keypair.fromSecretKey(seed);

const MilestoneReport = bcs.struct('MilestoneReport', {
  project_id: bcs.Address,
  milestone_index: bcs.u64(),
  liters_reading: bcs.u64(),
  timestamp_ms: bcs.u64(),
});

function encode(projectId: string, mi: bigint, liters: bigint, ts: bigint): Uint8Array {
  return MilestoneReport.serialize({
    project_id: projectId,
    milestone_index: mi,
    liters_reading: liters,
    timestamp_ms: ts,
  }).toBytes();
}

const hex = (u: Uint8Array) => 'x"' + Buffer.from(u).toString('hex') + '"';

async function sig(bytes: Uint8Array): Promise<Uint8Array> {
  const out = await keypair.sign(bytes);
  return out;
}

const pubkey = keypair.getPublicKey().toRawBytes();

// Happy path: milestone 0 (threshold 0), 60_000 liters.
const pHappy = encode(PROJECT_ID, 0n, 60_000n, TS);
// Below threshold: milestone 1 (threshold = target 100_000), only 50_000 liters.
const pLow = encode(PROJECT_ID, 1n, 50_000n, TS);
// Wrong project (validly signed, but wrong id).
const pWrong = encode(WRONG_PROJECT_ID, 0n, 60_000n, TS);
// Trailing bytes: happy payload + one junk byte, signed as a whole.
const pTrailing = new Uint8Array([...pHappy, 0xff]);

const sHappy = await sig(pHappy);
const sLow = await sig(pLow);
const sWrong = await sig(pWrong);
const sTrailing = await sig(pTrailing);

console.log('// === generated by scripts/gen_attestation_vector.ts ===');
console.log(`const PUBKEY: vector<u8> = ${hex(pubkey)};`);
console.log(`const SIG_HAPPY: vector<u8> = ${hex(sHappy)};`);
console.log(`const SIG_LOW: vector<u8> = ${hex(sLow)};`);
console.log(`const SIG_WRONG: vector<u8> = ${hex(sWrong)};`);
console.log(`const SIG_TRAILING: vector<u8> = ${hex(sTrailing)};`);
console.log('// sanity (payload hex, for cross-checking Move encode_report_for_testing):');
console.log(`//   pHappy    = ${Buffer.from(pHappy).toString('hex')}`);
console.log(`//   pHappy.len= ${pHappy.length} (expect 56)`);
