#[test_only]
module yeti_wells::attestation_tests;

use sui::test_scenario as ts;
use sui::bcs;
use sui::coin::{Self, Coin};
use sui::sui::SUI;
use yeti_wells::registry::{Self, Registry, AdminCap};
use yeti_wells::project::{Self, WaterProject};
use yeti_wells::donation;
use yeti_wells::impact_nft::{Self, ImpactNFT};
use yeti_wells::attestation::{Self, Enclave};
use yeti_wells::enclave;
use yeti_wells::enclave_app::{Self, AppWitness};

const ADMIN: address = @0xAD;
const ALICE: address = @0xA11CE;
const BOB: address = @0xB0B;
const PAYOUT: address = @0xBEEF;
const WRONG_PROJECT: address = @0xDEAD;
const TS_MS: u64 = 1_000;

// === ed25519 test vectors — generated by scripts/gen_attestation_vector.ts (deterministic sim seed) ===
// Tied to the DETERMINISTIC project id that setup() produces. If setup() changes, re-probe + regenerate.
const PUBKEY: vector<u8> = x"9c7aba247d4b9a8b79b56eab182574e5f8cd9540289a1f895a069e005b58b3ca";
// Phase 5/9: signatures over the Nautilus IntentMessage(MilestoneReport).
const SIG_V2_HAPPY: vector<u8> = x"96f28a60073e592cd00fb82217ee2f6d79b25683047eb264ef8f89c17309a9c53577fb138e4bbd84ca5db461c4198d37f06c787c851948056f9fac28b797f90b";
const SIG_V2_WRONG: vector<u8> = x"62b94c6082915c306f10570e1bb267a4760b7fa829fa64c41b6b2a046a824e0e423ee52c5f644305d552079277863bd3880eebeb3f5f3282755341c70b52c50a";
const SIG_V2_LOW: vector<u8> = x"d8607a64f0e22c6a81976cde50a6323be3b9730f2056ac34cab9ba27b493e8a144c89bf6705b856600be529c008a6bdd1d2fab02f29e6dcd0e2ee3444d464a0b";
const SIG_V2_OOB: vector<u8> = x"36f8db3e20b493f3a76ba1e12f8e73a422ab7e4e3a10ee6a63161ec0079ef271a55170ad0214a19a03fe08fecff35ea823bac2133319d3beb819a8cab0813805";

// Goal 6 SUI, target 100_000. create_for_testing milestones: index 0 threshold 0 / release 3 SUI;
// index 1 threshold 100_000 / release 3 SUI. Project id = 0x63d9a652…3975 (matches the vectors above).
fun setup(): ts::Scenario {
    let mut sc = ts::begin(ADMIN);
    registry::init_for_testing(ts::ctx(&mut sc));
    ts::next_tx(&mut sc, ADMIN);
    let mut reg = ts::take_shared<Registry>(&sc);
    project::create_for_testing(&mut reg, 6_000_000_000, 100_000, PAYOUT, ts::ctx(&mut sc));
    ts::return_shared(reg);
    sc
}

fun alice_donates(sc: &mut ts::Scenario, amount: u64) {
    ts::next_tx(sc, ALICE);
    let mut reg = ts::take_shared<Registry>(sc);
    let mut proj = ts::take_shared<WaterProject>(sc);
    let c = coin::mint_for_testing<SUI>(amount, ts::ctx(sc));
    donation::donate(&mut proj, &mut reg, c, ts::ctx(sc));
    ts::return_shared(proj);
    ts::return_shared(reg);
}

fun register_dev_enclave(sc: &mut ts::Scenario) {
    ts::next_tx(sc, ADMIN);
    let cap = enclave_app::new_cap_for_testing(ts::ctx(sc));
    enclave::register_enclave_dev(&cap, PUBKEY, ts::ctx(sc));
    transfer::public_transfer(cap, ADMIN);
}

/// SEC-01: bind the project to the registered dev enclave (mirrors create_project_v2 / set_enclave).
fun bind_enclave(sc: &mut ts::Scenario) {
    ts::next_tx(sc, ADMIN);
    let cap = ts::take_from_sender<AdminCap>(sc);
    let mut proj = ts::take_shared<WaterProject>(sc);
    let enc = ts::take_shared<enclave::Enclave<AppWitness>>(sc);
    project::set_enclave(&cap, &mut proj, object::id(&enc));
    ts::return_shared(enc);
    ts::return_shared(proj);
    ts::return_to_sender(sc, cap);
}

#[test]
fun test_bcs_roundtrip() {
    let addr = @0xCAFE;
    let payload = attestation::encode_report_for_testing(addr, 2, 50_000, 1_234_567);
    let mut r = bcs::new(payload);
    assert!(r.peel_address() == addr, 0);
    assert!(r.peel_u64() == 2, 1);
    assert!(r.peel_u64() == 50_000, 2);
    assert!(r.peel_u64() == 1_234_567, 3);
    assert!(r.into_remainder_bytes().is_empty(), 4);
}

#[test]
fun test_v2_intent_serde() {
    // Move IntentMessage(MilestoneReport) BCS must byte-match the TS/Rust signer (parity check).
    let bytes = attestation::encode_intent_for_testing(
        @0x63d9a65220318469fb169034d8a011eae3f014fed2a1f8c006183e2ece3c3975, 0, 60_000, 1_000);
    assert!(bytes == x"01e80300000000000063d9a65220318469fb169034d8a011eae3f014fed2a1f8c006183e2ece3c3975000000000000000060ea000000000000e803000000000000", 0);
}

// === INFO-01: the Phase-1 raw-ed25519 path is now permanently deprecated ===

#[test]
#[expected_failure(abort_code = attestation::E_DEPRECATED)]
fun test_submit_v1_deprecated_aborts() {
    let mut sc = setup();
    ts::next_tx(&mut sc, ADMIN);
    attestation::register_enclave_for_testing(PUBKEY, ts::ctx(&mut sc));
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enclave = ts::take_shared<Enclave>(&sc);
        // Any args — the deprecated body aborts before touching them.
        attestation::submit_attested_milestone(&mut proj, &mut reg, &enclave, vector[], vector[], ts::ctx(&mut sc));
        ts::return_shared(enclave);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

// === Phase 5/9: Nautilus IntentMessage verification (submit_attested_milestone_v2) ===

#[test]
fun test_submit_v2_happy_path() {
    let mut sc = setup();
    alice_donates(&mut sc, 6_000_000_000);
    register_dev_enclave(&mut sc);
    bind_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enc = ts::take_shared<enclave::Enclave<AppWitness>>(&sc);
        let pid = object::id_address(&proj);
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, pid, 0, 60_000, SIG_V2_HAPPY, ts::ctx(&mut sc));
        assert!(project::delivered_liters(&proj) == 60_000, 0);
        assert!(project::milestone_released(&proj, 0), 1);
        assert!(project::escrow_value(&proj) == 3_000_000_000, 2);
        ts::return_shared(enc);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    // payout received the released 3 SUI.
    ts::next_tx(&mut sc, PAYOUT);
    {
        let paid = ts::take_from_sender<Coin<SUI>>(&sc);
        assert!(coin::value(&paid) == 3_000_000_000, 3);
        ts::return_to_sender(&sc, paid);
    };
    ts::end(sc);
}

#[test]
#[expected_failure(abort_code = attestation::E_BAD_SIGNATURE)]
fun test_submit_v2_bad_sig_aborts() {
    let mut sc = setup();
    register_dev_enclave(&mut sc);
    bind_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enc = ts::take_shared<enclave::Enclave<AppWitness>>(&sc);
        let mut bad = SIG_V2_HAPPY;
        let b0 = *vector::borrow(&bad, 0);
        *vector::borrow_mut(&mut bad, 0) = b0 ^ 1u8;
        let pid = object::id_address(&proj);
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, pid, 0, 60_000, bad, ts::ctx(&mut sc));
        ts::return_shared(enc);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

#[test]
#[expected_failure(abort_code = attestation::E_WRONG_PROJECT)]
fun test_submit_v2_wrong_project_aborts() {
    let mut sc = setup();
    register_dev_enclave(&mut sc);
    bind_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enc = ts::take_shared<enclave::Enclave<AppWitness>>(&sc);
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, WRONG_PROJECT, 0, 60_000, SIG_V2_WRONG, ts::ctx(&mut sc));
        ts::return_shared(enc);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

// SEC-01 core: a valid signature for the right project still fails if the project isn't bound to THIS enclave.
#[test]
#[expected_failure(abort_code = attestation::E_WRONG_ENCLAVE)]
fun test_submit_v2_unbound_enclave_aborts() {
    let mut sc = setup();
    alice_donates(&mut sc, 6_000_000_000);
    register_dev_enclave(&mut sc); // registered but NOT bound to the project
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enc = ts::take_shared<enclave::Enclave<AppWitness>>(&sc);
        let pid = object::id_address(&proj);
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, pid, 0, 60_000, SIG_V2_HAPPY, ts::ctx(&mut sc));
        ts::return_shared(enc);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

#[test]
#[expected_failure(abort_code = attestation::E_BELOW_THRESHOLD)]
fun test_submit_v2_below_threshold_aborts() {
    let mut sc = setup();
    alice_donates(&mut sc, 6_000_000_000);
    register_dev_enclave(&mut sc);
    bind_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enc = ts::take_shared<enclave::Enclave<AppWitness>>(&sc);
        let pid = object::id_address(&proj);
        // milestone 1 threshold = 100_000; reading only 50_000.
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, pid, 1, 50_000, SIG_V2_LOW, ts::ctx(&mut sc));
        ts::return_shared(enc);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

#[test]
#[expected_failure(abort_code = attestation::E_INDEX_OOB)]
fun test_submit_v2_oob_index_aborts() {
    let mut sc = setup();
    alice_donates(&mut sc, 6_000_000_000);
    register_dev_enclave(&mut sc);
    bind_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enc = ts::take_shared<enclave::Enclave<AppWitness>>(&sc);
        let pid = object::id_address(&proj);
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, pid, 5, 60_000, SIG_V2_OOB, ts::ctx(&mut sc));
        ts::return_shared(enc);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

#[test]
#[expected_failure(abort_code = attestation::E_ALREADY_RELEASED)]
fun test_submit_v2_double_release_aborts() {
    let mut sc = setup();
    alice_donates(&mut sc, 6_000_000_000);
    register_dev_enclave(&mut sc);
    bind_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enc = ts::take_shared<enclave::Enclave<AppWitness>>(&sc);
        let pid = object::id_address(&proj);
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, pid, 0, 60_000, SIG_V2_HAPPY, ts::ctx(&mut sc));
        // second release of the same milestone -> aborts
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, pid, 0, 60_000, SIG_V2_HAPPY, ts::ctx(&mut sc));
        ts::return_shared(enc);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

// SEC-02 clamp: an under-funded milestone releases only the available escrow instead of aborting.
#[test]
fun test_submit_v2_underfunded_clamp() {
    let mut sc = setup();
    alice_donates(&mut sc, 1_000_000_000); // 1 SUI < milestone 0 nominal release of 3 SUI
    register_dev_enclave(&mut sc);
    bind_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enc = ts::take_shared<enclave::Enclave<AppWitness>>(&sc);
        let pid = object::id_address(&proj);
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, pid, 0, 60_000, SIG_V2_HAPPY, ts::ctx(&mut sc));
        assert!(project::milestone_released(&proj, 0), 0);
        assert!(project::escrow_value(&proj) == 0, 1); // clamped: released all 1 SUI, no abort
        ts::return_shared(enc);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::next_tx(&mut sc, PAYOUT);
    {
        let paid = ts::take_from_sender<Coin<SUI>>(&sc);
        assert!(coin::value(&paid) == 1_000_000_000, 2);
        ts::return_to_sender(&sc, paid);
    };
    ts::end(sc);
}

// ECON-02: a later donation that dilutes `raised` must NOT shrink an earlier donor's attributed liters.
#[test]
fun test_attribution_monotonic_after_dilution() {
    let mut sc = setup();
    alice_donates(&mut sc, 6_000_000_000); // raised 6 SUI, Alice donated 6 SUI
    register_dev_enclave(&mut sc);
    bind_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enc = ts::take_shared<enclave::Enclave<AppWitness>>(&sc);
        let pid = object::id_address(&proj);
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, pid, 0, 60_000, SIG_V2_HAPPY, ts::ctx(&mut sc));
        ts::return_shared(enc);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    // Alice syncs: 60_000 * 6e9 / 6e9 = 60_000.
    ts::next_tx(&mut sc, ALICE);
    {
        let proj = ts::take_shared<WaterProject>(&sc);
        let mut nft = ts::take_from_sender<ImpactNFT>(&sc);
        impact_nft::sync_impact(&mut nft, &proj);
        assert!(impact_nft::liters_attributed(&nft) == 60_000, 0);
        ts::return_to_sender(&sc, nft);
        ts::return_shared(proj);
    };
    // Bob donates 6 SUI -> raised 12 SUI (dilutes the denominator).
    ts::next_tx(&mut sc, BOB);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let c = coin::mint_for_testing<SUI>(6_000_000_000, ts::ctx(&mut sc));
        donation::donate(&mut proj, &mut reg, c, ts::ctx(&mut sc));
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    // Alice re-syncs: computed would be 30_000, but monotonic clamp keeps 60_000.
    ts::next_tx(&mut sc, ALICE);
    {
        let proj = ts::take_shared<WaterProject>(&sc);
        let mut nft = ts::take_from_sender<ImpactNFT>(&sc);
        impact_nft::sync_impact(&mut nft, &proj);
        assert!(impact_nft::liters_attributed(&nft) == 60_000, 1); // did NOT regress to 30_000
        ts::return_to_sender(&sc, nft);
        ts::return_shared(proj);
    };
    ts::end(sc);
}
