#[test_only]
module yeti_wells::attestation_tests;

use sui::test_scenario as ts;
use sui::bcs;
use sui::coin::{Self, Coin};
use sui::sui::SUI;
use yeti_wells::registry::{Self, Registry};
use yeti_wells::project::{Self, WaterProject};
use yeti_wells::donation;
use yeti_wells::attestation::{Self, Enclave};
use yeti_wells::enclave;
use yeti_wells::enclave_app::{Self, AppWitness};

const ADMIN: address = @0xAD;
const ALICE: address = @0xA11CE;
const PAYOUT: address = @0xBEEF;
const WRONG_PROJECT: address = @0xDEAD;
const TS_MS: u64 = 1_000;

// === ed25519 test vectors — generated by scripts/gen_attestation_vector.ts ===
// Tied to the DETERMINISTIC project id that setup() produces (see probe note below).
// If setup() changes, re-probe the id and regenerate these.
const PUBKEY: vector<u8> = x"9c7aba247d4b9a8b79b56eab182574e5f8cd9540289a1f895a069e005b58b3ca";
const SIG_HAPPY: vector<u8> = x"6a629f7f686a848d79f0fb6a92af0ef067d2391a4a16323f90e9fb30aa4db27e599801e0b303a1ef95c8909bc8ea8411edc1ac8b550ede333ed05de502256401";
const SIG_LOW: vector<u8> = x"f6a00262ac66450784ff6fc85c267e9129f3b297a2e0cb97ff1c87a75c848d73a347ab66495ecf8b4f56518cbdd995c6a096cf2ad8fa98325f427ef21b08d603";
const SIG_WRONG: vector<u8> = x"f33c0c8edbd48efdb2b793177fffe03774b045c33fb1be283bfe924b6736f27f17a37c8eb08a6aaf3adf572553801cd5dc58c73ddaf4fd3e34bb579baeaacf0a";
const SIG_TRAILING: vector<u8> = x"bb27c25551f06e4e9b6486384756978aea192cc2909846bf53eab30cc9c813474697fefe5756f22e92d8e70f0893f2e90214ec194c9cc6172c9b59829837e10e";
// Phase 5: signatures over the Nautilus IntentMessage(MilestoneReport).
const SIG_V2_HAPPY: vector<u8> = x"96f28a60073e592cd00fb82217ee2f6d79b25683047eb264ef8f89c17309a9c53577fb138e4bbd84ca5db461c4198d37f06c787c851948056f9fac28b797f90b";
const SIG_V2_WRONG: vector<u8> = x"62b94c6082915c306f10570e1bb267a4760b7fa829fa64c41b6b2a046a824e0e423ee52c5f644305d552079277863bd3880eebeb3f5f3282755341c70b52c50a";

// Deterministic setup. Goal 6 SUI, target 100_000. create_for_testing milestones:
// index 0: threshold 0, release 3 SUI ; index 1: threshold 100_000, release 3 SUI.
// Resulting WaterProject id = 0x63d9a65220318469fb169034d8a011eae3f014fed2a1f8c006183e2ece3c3975.
fun setup(): ts::Scenario {
    let mut sc = ts::begin(ADMIN);
    registry::init_for_testing(ts::ctx(&mut sc));
    ts::next_tx(&mut sc, ADMIN);
    let mut reg = ts::take_shared<Registry>(&sc);
    project::create_for_testing(&mut reg, 6_000_000_000, 100_000, PAYOUT, ts::ctx(&mut sc));
    ts::return_shared(reg);
    sc
}

fun alice_donates(sc: &mut ts::Scenario, amount: u64) {
    ts::next_tx(sc, ALICE);
    let mut reg = ts::take_shared<Registry>(sc);
    let mut proj = ts::take_shared<WaterProject>(sc);
    let c = coin::mint_for_testing<SUI>(amount, ts::ctx(sc));
    donation::donate(&mut proj, &mut reg, c, ts::ctx(sc));
    ts::return_shared(proj);
    ts::return_shared(reg);
}

fun register_enclave(sc: &mut ts::Scenario) {
    ts::next_tx(sc, ADMIN);
    attestation::register_enclave_for_testing(PUBKEY, ts::ctx(sc));
}

#[test]
fun test_bcs_roundtrip() {
    let addr = @0xCAFE;
    let payload = attestation::encode_report_for_testing(addr, 2, 50_000, 1_234_567);
    let mut r = bcs::new(payload);
    assert!(r.peel_address() == addr, 0);
    assert!(r.peel_u64() == 2, 1);
    assert!(r.peel_u64() == 50_000, 2);
    assert!(r.peel_u64() == 1_234_567, 3);
    assert!(r.into_remainder_bytes().is_empty(), 4);
}

#[test]
fun test_submit_happy_path() {
    let mut sc = setup();
    alice_donates(&mut sc, 6_000_000_000);
    register_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enclave = ts::take_shared<Enclave>(&sc);
        let payload = attestation::encode_report_for_testing(object::id_address(&proj), 0, 60_000, TS_MS);
        attestation::submit_attested_milestone(&mut proj, &mut reg, &enclave, payload, SIG_HAPPY, ts::ctx(&mut sc));
        assert!(project::delivered_liters(&proj) == 60_000, 0);
        assert!(registry::total_delivered_liters(&reg) == 60_000, 1);
        assert!(project::escrow_value(&proj) == 3_000_000_000, 2); // 6 SUI - 3 SUI released
        assert!(project::milestone_released(&proj, 0), 3);
        ts::return_shared(enclave);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    // The payout partner received a Coin<SUI> of the released amount.
    ts::next_tx(&mut sc, PAYOUT);
    {
        let paid = ts::take_from_sender<Coin<SUI>>(&sc);
        assert!(coin::value(&paid) == 3_000_000_000, 4);
        ts::return_to_sender(&sc, paid);
    };
    ts::end(sc);
}

#[test]
#[expected_failure(abort_code = attestation::E_BAD_SIGNATURE)]
fun test_submit_bad_signature_aborts() {
    let mut sc = setup();
    register_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enclave = ts::take_shared<Enclave>(&sc);
        let payload = attestation::encode_report_for_testing(object::id_address(&proj), 0, 60_000, TS_MS);
        let mut bad = SIG_HAPPY;
        let b0 = *vector::borrow(&bad, 0);
        *vector::borrow_mut(&mut bad, 0) = b0 ^ 1u8; // corrupt one byte
        attestation::submit_attested_milestone(&mut proj, &mut reg, &enclave, payload, bad, ts::ctx(&mut sc));
        ts::return_shared(enclave);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

#[test]
#[expected_failure(abort_code = attestation::E_WRONG_PROJECT)]
fun test_submit_wrong_project_aborts() {
    let mut sc = setup();
    register_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enclave = ts::take_shared<Enclave>(&sc);
        // Validly signed, but for a DIFFERENT project id.
        let payload = attestation::encode_report_for_testing(WRONG_PROJECT, 0, 60_000, TS_MS);
        attestation::submit_attested_milestone(&mut proj, &mut reg, &enclave, payload, SIG_WRONG, ts::ctx(&mut sc));
        ts::return_shared(enclave);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

#[test]
#[expected_failure(abort_code = attestation::E_BELOW_THRESHOLD)]
fun test_submit_below_threshold_aborts() {
    let mut sc = setup();
    register_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enclave = ts::take_shared<Enclave>(&sc);
        // milestone 1 threshold is 100_000; reading only 50_000.
        let payload = attestation::encode_report_for_testing(object::id_address(&proj), 1, 50_000, TS_MS);
        attestation::submit_attested_milestone(&mut proj, &mut reg, &enclave, payload, SIG_LOW, ts::ctx(&mut sc));
        ts::return_shared(enclave);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

#[test]
#[expected_failure(abort_code = attestation::E_TRAILING_BYTES)]
fun test_submit_trailing_bytes_aborts() {
    let mut sc = setup();
    register_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enclave = ts::take_shared<Enclave>(&sc);
        let mut payload = attestation::encode_report_for_testing(object::id_address(&proj), 0, 60_000, TS_MS);
        vector::push_back(&mut payload, 0xffu8); // signed-over junk byte
        attestation::submit_attested_milestone(&mut proj, &mut reg, &enclave, payload, SIG_TRAILING, ts::ctx(&mut sc));
        ts::return_shared(enclave);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

#[test]
#[expected_failure(abort_code = attestation::E_ALREADY_RELEASED)]
fun test_submit_double_release_aborts() {
    let mut sc = setup();
    alice_donates(&mut sc, 6_000_000_000);
    register_enclave(&mut sc);
    // First (successful) release of milestone 0.
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enclave = ts::take_shared<Enclave>(&sc);
        let payload = attestation::encode_report_for_testing(object::id_address(&proj), 0, 60_000, TS_MS);
        attestation::submit_attested_milestone(&mut proj, &mut reg, &enclave, payload, SIG_HAPPY, ts::ctx(&mut sc));
        ts::return_shared(enclave);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    // Second submit of the same milestone -> aborts.
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enclave = ts::take_shared<Enclave>(&sc);
        let payload = attestation::encode_report_for_testing(object::id_address(&proj), 0, 60_000, TS_MS);
        attestation::submit_attested_milestone(&mut proj, &mut reg, &enclave, payload, SIG_HAPPY, ts::ctx(&mut sc));
        ts::return_shared(enclave);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

// === Phase 5: real Nautilus IntentMessage verification (submit_attested_milestone_v2) ===

#[test]
fun test_v2_intent_serde() {
    // Move IntentMessage(MilestoneReport) BCS must byte-match the TS/Rust signer (parity check).
    let bytes = attestation::encode_intent_for_testing(
        @0x63d9a65220318469fb169034d8a011eae3f014fed2a1f8c006183e2ece3c3975, 0, 60_000, 1_000);
    assert!(bytes == x"01e80300000000000063d9a65220318469fb169034d8a011eae3f014fed2a1f8c006183e2ece3c3975000000000000000060ea000000000000e803000000000000", 0);
}

fun register_dev_enclave(sc: &mut ts::Scenario) {
    ts::next_tx(sc, ADMIN);
    let cap = enclave_app::new_cap_for_testing(ts::ctx(sc));
    enclave::register_enclave_dev(&cap, PUBKEY, ts::ctx(sc));
    transfer::public_transfer(cap, ADMIN);
}

#[test]
fun test_submit_v2_happy_path() {
    let mut sc = setup();
    alice_donates(&mut sc, 6_000_000_000);
    register_dev_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enc = ts::take_shared<enclave::Enclave<AppWitness>>(&sc);
        let pid = object::id_address(&proj);
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, pid, 0, 60_000, SIG_V2_HAPPY, ts::ctx(&mut sc));
        assert!(project::delivered_liters(&proj) == 60_000, 0);
        assert!(project::milestone_released(&proj, 0), 1);
        assert!(project::escrow_value(&proj) == 3_000_000_000, 2);
        ts::return_shared(enc);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

#[test]
#[expected_failure(abort_code = attestation::E_BAD_SIGNATURE)]
fun test_submit_v2_bad_sig_aborts() {
    let mut sc = setup();
    register_dev_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enc = ts::take_shared<enclave::Enclave<AppWitness>>(&sc);
        let mut bad = SIG_V2_HAPPY;
        let b0 = *vector::borrow(&bad, 0);
        *vector::borrow_mut(&mut bad, 0) = b0 ^ 1u8;
        let pid = object::id_address(&proj);
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, pid, 0, 60_000, bad, ts::ctx(&mut sc));
        ts::return_shared(enc);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}

#[test]
#[expected_failure(abort_code = attestation::E_WRONG_PROJECT)]
fun test_submit_v2_wrong_project_aborts() {
    let mut sc = setup();
    register_dev_enclave(&mut sc);
    ts::next_tx(&mut sc, ADMIN);
    {
        let mut reg = ts::take_shared<Registry>(&sc);
        let mut proj = ts::take_shared<WaterProject>(&sc);
        let enc = ts::take_shared<enclave::Enclave<AppWitness>>(&sc);
        attestation::submit_attested_milestone_v2(
            &mut proj, &mut reg, &enc, TS_MS, WRONG_PROJECT, 0, 60_000, SIG_V2_WRONG, ts::ctx(&mut sc));
        ts::return_shared(enc);
        ts::return_shared(proj);
        ts::return_shared(reg);
    };
    ts::end(sc);
}
